import { useState, useEffect } from 'react'
import { apiService } from '../services/api.js'
import { authService } from '../services/auth.js'
import NavBar from '../components/NavBar.jsx'
import './cheat-sheet.css'

export default function CheatSheet() {
  const [data, setData] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')

  useEffect(() => {
    if (!authService.isAuthenticated()) {
      setError('Please log in to view your cheat sheet')
      setLoading(false)
      return
    }
    ;(async () => {
      try {
        const sheet = await apiService.getCheatSheet()
        setData(sheet)
      } catch (err) {
        setError(err.message)
      } finally {
        setLoading(false)
      }
    })()
  }, [])

  if (loading) return <div className="cs-page"><NavBar /><p className="cs-loading">Loading...</p></div>
  if (error) return <div className="cs-page"><NavBar /><p className="cs-error">{error}</p></div>
  if (!data) return null

  return (
    <div className="cs-page">
      <NavBar />

      <main className="cs-main">
        <header className="cs-header">
          <h1 className="cs-title">Caregiver Cheat Sheet</h1>
          <p className="cs-child-name">
            For {data.child_name}
            {data.child_age ? `, age ${data.child_age}` : ''}
          </p>
        </header>

        {data.approved_channels.length > 0 && (
          <section className="cs-section cs-approved">
            <h2 className="cs-section-title">Approved Channels</h2>
            <p className="cs-section-desc">
              These channels are age-appropriate and safe for viewing.
            </p>
            <ul className="cs-list">
              {data.approved_channels.map(ch => (
                <li key={ch.name} className="cs-item">
                  <span className={`cs-dot cs-dot-${ch.tier}`} />
                  <span className="cs-item-name">{ch.name}</span>
                  <span className="cs-item-tier">{ch.tier}</span>
                </li>
              ))}
            </ul>
          </section>
        )}

        {data.avoid_channels.length > 0 && (
          <section className="cs-section cs-avoid">
            <h2 className="cs-section-title">Channels to Avoid</h2>
            <p className="cs-section-desc">
              These channels have content patterns that may not be ideal.
            </p>
            <ul className="cs-list">
              {data.avoid_channels.map(ch => (
                <li key={ch.name} className="cs-item">
                  <span className="cs-dot cs-dot-junk" />
                  <span className="cs-item-name">{ch.name}</span>
                  {ch.reason && (
                    <span className="cs-item-reason">{ch.reason}</span>
                  )}
                </li>
              ))}
            </ul>
          </section>
        )}

        {data.viewing_rules.length > 0 && (
          <section className="cs-section cs-rules">
            <h2 className="cs-section-title">Viewing Rules</h2>
            <ol className="cs-rules-list">
              {data.viewing_rules.map((rule, i) => (
                <li key={i} className="cs-rule">{rule}</li>
              ))}
            </ol>
          </section>
        )}

        <div className="cs-actions no-print">
          <button className="cs-print-btn" onClick={() => window.print()}>
            Print This Page
          </button>
          <a href="/summary" className="cs-back-link">Back to Dashboard</a>
        </div>

        <footer className="cs-footer">
          <span>Generated by Tedio</span>
        </footer>
      </main>
    </div>
  )
}
